name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Show CMake version
        run: cmake --version
      - name: Show Python version
        run: python --version
      - name: Build
        run: |
          cmake .
          make
          du -h tmp/libskia.a
          du -h lib/libemoji.a
